baseURL = 'https://xch.name/'
locale = 'zh'
title = '星辰'
theme = 'PaperMod'
hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[pagination]
  pagerSize = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'

[permalinks]
  posts = '/archives/:slug/'
  pages = '/:slug/'
  categories = '/category/:slug/'
  tags = '/tag/:slug/'

[[menu.main]]
  name = '归档'
  url = '/archives/'
  weight = 1

[[menu.main]]
  name = '分类'
  url = '/categories/'
  weight = 2

[[menu.main]]
  name = '标签'
  url = '/tags/'
  weight = 3

[[menu.main]]
  name = '关于'
  url = '/about/'
  weight = 4

[params]
  defaultTheme = "auto"
  [params.assets]
    favicon = "favicon.ico"
  description = "刘星辰的个人主页"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = true
  UseHugoToc = true
  comments = false

[params.homeInfoParams]
  Title = "星辰 ✨"
  Content = "刘星辰的个人主页"

